dataset_class: AlzheimerMRI
data_dir: ./datasets/Alzheimer_MRI_4_classes_dataset
random_seeds: [42]

c_values: [0.5]
scenarios: [case-control]
selection_strategies: ["random"]

val_ratio: 0.1
target_prevalence: 0.5
with_replacement: true
also_print_dataset_stats: false

label_scheme:
  positive_classes: ["NonDemented"]
  negative_classes: ["VeryMildDemented", "ModerateDemented", "MildDemented"]

image_size: [128, 128]
